version: "3.8"

services:
  mongodb-test:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  express-app:
    build: .
    container_name: express-app
    restart: unless-stopped
    depends_on:
      - mongodb-test
    environment:
      PORT: ${PORT}
      MONGO_DB_URL: mongodb://${MONGO_DB_USER}:${MONGO_DB_PASSWORD}@mongodb-test:27017/${MONGO_DB_NAME}?authSource=admin
    ports:
      - "${PORT}:3000"

volumes:
  mongo-data:
